global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: 'codelab-monitor'
scrape_configs:
  - job_name: 'GosTech Dummy Service'

    scrape_interval: 1s

    static_configs:
      - targets: ['host.docker.internal:5000']